import 'dart:ui' as ui show FontFeature, FontVariation, Shadow, TextLeadingDistribution;

import 'package:flutter/material.dart';
import 'package:ui_kit/ui_kit.dart';

class UIKitText extends Text {
  const UIKitText(super.data, {super.key});

  UIKitText.displayLarge(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.displayLarge(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.displayMedium(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.displayMedium(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.displaySmall(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.displaySmall(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.headlineLarge(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.headlineLarge(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.headlineMedium(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.headlineMedium(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.headlineSmall(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.headlineSmall(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.titleLarge(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.titleLarge(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.titleMedium(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.titleMedium(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.titleSmall(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.titleSmall(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.labelLarge(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.labelLarge(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.labelMedium(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.labelMedium(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.labelSmall(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.labelSmall(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.bodyLarge(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.bodyLarge(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.bodyMedium(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.bodyMedium(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  UIKitText.bodySmall(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    UIKitFontWeight? fontWeight,
    UIKitFontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: UIKitTextStyle.bodySmall(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );
}
