name: base_template
description: A new flutter project

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Custom packages
  ui_kit:
    path: ./packages/ui_kit

  # Localization
  flutter_localizations:
    sdk: flutter
  slang: ^4.8.1
  slang_flutter: ^4.8.0

  # Networking
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  pretty_dio_logger: ^1.4.0

  # Caching
  shared_preferences: ^2.5.3

  # Routing
  auto_route: ^9.2.2

  # State management
  flutter_bloc: ^9.1.1

  # Data class generation
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Functional programming
  fpdart: ^1.1.1

  # Utility
  uuid: ^4.5.1
  intl: ^0.20.2
  logger: ^2.6.1
  envied: ^1.1.0
  package_info_plus: ^8.3.0
  device_info_plus: ^11.5.0

  # Dependency Injection
  get_it: ^8.2.0

  # App Icons
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linter
  very_good_analysis: ^9.0.0

  # Code Generation
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  envied_generator: ^1.1.0
  auto_route_generator: ^9.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  image_path: "assets/icons/app_icon/logo.png"
  adaptive_icon_background: "#FFFFFF"
  # Padding 8%
  adaptive_icon_foreground: "assets/icons/app_icon/logo_foreground.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  image: "assets/icons/logo_no_bg.png"
  android_12:
    image: "assets/icons/logo_12_no_bg.png"
    color: "#FFFFFF"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/app_icon/
