name: {{project_name.snakeCase()}}
description: {{description.sentenceCase()}}

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  slang: ^4.1.0
  slang_flutter: ^4.1.0

  # Networking
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  pretty_dio_logger: ^1.4.0

  # Caching
  shared_preferences: ^2.3.3

  # Routing
  auto_route: ^9.2.2

  # State management
  flutter_bloc: ^8.1.6

  # Data class generation
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Functional programming
  fpdart: ^1.1.0

  # Utility
  uuid: ^4.5.1
  intl: ^0.19.0
  logger: ^2.4.0
  envied: ^0.5.4+1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2

  # Dependency Injection
  get_it: ^8.0.0

  # App Icons
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linter
  very_good_analysis: ^6.0.0

  # Code Generation
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1
  auto_route_generator: ^9.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  image_path: "assets/icons/app_icon/logo.png"
  adaptive_icon_background: "#FFFFFF"
  # Padding 8%
  adaptive_icon_foreground: "assets/icons/app_icon/logo_foreground.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  image: "assets/icons/logo_no_bg.png"
  android_12:
    image: "assets/icons/logo_12_no_bg.png"
    color: "#FFFFFF"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/app_icon/
