import 'dart:ui' as ui show FontFeature, FontVariation, Shadow, TextLeadingDistribution;

import 'package:flutter/material.dart';
import 'package:{{class_name.snakeCase()}}/{{class_name.snakeCase()}}.dart';

class {{class_name.pascalCase()}}Text extends Text {
  const {{class_name.pascalCase()}}Text(super.data, {super.key});

  {{class_name.pascalCase()}}Text.displayLarge(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.displayLarge(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.displayMedium(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.displayMedium(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.displaySmall(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.displaySmall(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.headlineLarge(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.headlineLarge(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.headlineMedium(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.headlineMedium(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.headlineSmall(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.headlineSmall(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.titleLarge(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.titleLarge(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.titleMedium(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.titleMedium(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.titleSmall(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.titleSmall(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.labelLarge(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.labelLarge(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.labelMedium(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.labelMedium(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.labelSmall(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.labelSmall(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.bodyLarge(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.bodyLarge(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.bodyMedium(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.bodyMedium(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );

  {{class_name.pascalCase()}}Text.bodySmall(
    BuildContext context,
    super.data, {
    super.key,
    Color? color,
    FontStyle? fontStyle,
    double? lineHeight,
    super.maxLines,
    super.overflow,
    super.locale,
    super.selectionColor,
    super.semanticsLabel,
    super.softWrap,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.textHeightBehavior,
    double? textScaleFactor,
    super.textWidthBasis,
    {{class_name.pascalCase()}}FontWeight? fontWeight,
    {{class_name.pascalCase()}}FontFamily? fontFamily,
    bool? inherit,
    Color? backgroundColor,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    ui.TextLeadingDistribution? leadingDistribution,
    Paint? foreground,
    Paint? background,
    List<ui.Shadow>? shadows,
    List<ui.FontFeature>? fontFeatures,
    List<ui.FontVariation>? fontVariations,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
  }) : super(
          style: {{class_name.pascalCase()}}TextStyle.bodySmall(
            context,
            color: color,
            fontStyle: fontStyle,
            lineHeight: lineHeight,
            fontWeight: fontWeight,
            fontFamily: fontFamily,
            inherit: inherit,
            backgroundColor: backgroundColor,
            letterSpacing: letterSpacing,
            wordSpacing: wordSpacing,
            textBaseline: textBaseline,
            leadingDistribution: leadingDistribution,
            foreground: foreground,
            background: background,
            shadows: shadows,
            fontFeatures: fontFeatures,
            fontVariations: fontVariations,
            decoration: decoration,
            decorationColor: decorationColor,
            decorationStyle: decorationStyle,
            decorationThickness: decorationThickness,
            debugLabel: debugLabel,
            locale: locale,
            overflow: overflow,
          ),
          textScaler: textScaleFactor != null ? TextScaler.linear(textScaleFactor) : null,
        );
}
